from models.discriminators.largefov import LargeFOV
from models.discriminators.largefov_light import LargeFOVLight
from models.discriminators.smallfov import SmallFOV
from models.discriminators.smallfov_light import SmallFOVLight
from models.discriminators.spp_discriminator import SPPDiscriminator
